# Generated by Django 5.0.2 on 2025-11-13 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0003_alumnos_maestros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='administradores',
            old_name='ocupacion',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='curp',
            new_name='departamento',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='telefono',
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_trabajador', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Maestros',
        ),
    ]
